# Generated by Django 4.2.14 on 2024-07-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.CharField(max_length=10)),
                ('input_string', models.CharField(max_length=100)),
                ('output', models.CharField(max_length=15)),
            ],
        ),
    ]
